### ISSUE TITLE
Sedona Flink Function Not Found Error When Deployed on Distributed Cluster

### ISSUE THREAD

**Issue by wang0702** [apache/sedona#1052]
## Actual behavior
Sedona Flink works fine in my local IDE, but when I try to deploy it to a distributed cluster, I get a "function not found" error.
## Settings

Sedona version = 1.4.1

Apache Spark version = 3.0

Apache Flink version = 1.43

API type = Scala, Java, Python?

Scala version =2.12

JRE version = 1.8

Python version = 3.7

Environment = Standalone or flink cluster

<img width="1305" alt="image" src="https://github.com/apache/sedona/assets/30549049/66c305a2-0368-4357-9ef6-dbfb4476685a">

**Comment by jiayuasu** [comment]
Please make sure you correctly package your code to a fat jar. If you use Maven, please use maven shaded plugin. If you use sbt, please use sbt assembly plugin.

But from the error message, it seems that you didn't correctly register Sedona Flink functions to Flink.

**Comment by wang0702** [comment]
I just used the sedona example/flink-sql program to package, it works fine in IDEA locally. But cannot depoly to the cluster. I already used the maven shaded plugin right now. Could you please give me more suggestions.

org.apache.flink.runtime.rest.handler.RestHandlerException: Could not execute application. at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$1(JarRunHandler.java:110) at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836) at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) at java.lang.Thread.run(Thread.java:750) Caused by: java.util.concurrent.CompletionException: org.apache.flink.util.FlinkRuntimeException: Could not execute application. at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) ... 1 more Caused by: org.apache.flink.util.FlinkRuntimeException: Could not execute application. at org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:88) at org.apache.flink.client.deployment.application.DetachedApplicationRunner.run(DetachedApplicationRunner.java:70) at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$0(JarRunHandler.java:104) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ... 1 more Caused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Invalid function call: ST_S2CellIDs(RAW('org.locationtech.jts.geom.Geometry', '...'), INT NOT NULL) at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372) at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) at org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:84) ... 4 more Caused by: org.apache.flink.table.api.ValidationException: Invalid function call: ST_S2CellIDs(RAW('org.locationtech.jts.geom.Geometry', '...'), INT NOT NULL) at org.apache.flink.table.types.inference.TypeInferenceUtil.createInvalidCallException(TypeInferenceUtil.java:194) at org.apache.flink.table.planner.functions.inference.TypeInferenceReturnInference.inferReturnType(TypeInferenceReturnInference.java:78) at org.apache.calcite.sql.SqlOperator.inferReturnType(SqlOperator.java:482) at org.apache.calcite.rex.RexBuilder.deriveReturnType(RexBuilder.java:283) at org.apache.calcite.tools.RelBuilder.call(RelBuilder.java:595) at org.apache.calcite.tools.RelBuilder.call(RelBuilder.java:602) at org.apache.flink.table.planner.expressions.converter.FunctionDefinitionConvertRule.convert(FunctionDefinitionConvertRule.java:73) at org.apache.flink.table.planner.expressions.converter.ExpressionConverter.visit(ExpressionConverter.java:97) at org.apache.flink.table.planner.expressions.converter.ExpressionConverter.visit(ExpressionConverter.java:71) at org.apache.flink.table.expressions.CallExpression.accept(CallExpression.java:134) at org.apache.flink.table.planner.plan.QueryOperationConverter.convertExprToRexNode(QueryOperationConverter.java:857) at org.apache.flink.table.planner.plan.QueryOperationConverter.access$800(QueryOperationConverter.java:134) at org.apache.flink.table.planner.plan.QueryOperationConverter$SingleRelVisitor.lambda$convertToRexNodes$6(QueryOperationConverter.java:630) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) at org.apache.flink.table.planner.plan.QueryOperationConverter$SingleRelVisitor.convertToRexNodes(QueryOperationConverter.java:631) at org.apache.flink.table.planner.plan.QueryOperationConverter$SingleRelVisitor.visit(QueryOperationConverter.java:158) at org.apache.flink.table.planner.plan.QueryOperationConverter$SingleRelVisitor.visit(QueryOperationConverter.java:154) at org.apache.flink.table.operations.ProjectQueryOperation.accept(ProjectQueryOperation.java:76) at org.apache.flink.table.planner.plan.QueryOperationConverter.defaultMethod(QueryOperationConverter.java:151) at org.apache.flink.table.planner.plan.QueryOperationConverter.defaultMethod(QueryOperationConverter.java:133) at org.apache.flink.table.operations.utils.QueryOperationDefaultVisitor.visit(QueryOperationDefaultVisitor.java:47) at org.apache.flink.table.operations.ProjectQueryOperation.accept(ProjectQueryOperation.java:76) at org.apache.flink.table.planner.calcite.FlinkRelBuilder.queryOperation(FlinkRelBuilder.scala:184) at org.apache.flink.table.planner.catalog.QueryOperationCatalogViewTable.convertToRel(QueryOperationCatalogViewTable.java:76) at org.apache.flink.table.planner.plan.schema.ExpandingPreparingTable.expand(ExpandingPreparingTable.java:59) at org.apache.flink.table.planner.plan.schema.ExpandingPreparingTable.toRel(ExpandingPreparingTable.java:55) at org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3585) at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2507) at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2144) at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2093) at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2050) at org.apache.calcite.sql2rel.SqlToRelConverter.convertJoin(SqlToRelConverter.java:2864) at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2162) at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2050) at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:663) at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:644) at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3438) at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:570) at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:177) at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:169) at org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:1057) at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:1026) at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:301) at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:101) at org.apache.flink.table.api.internal.TableEnvironmentImpl.sqlQuery(TableEnvironmentImpl.java:716) at FlinkExample.main(FlinkExample.java:55) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ... 7 more Caused by: org.apache.flink.table.api.ValidationException: Could not infer an output type for the given arguments. at org.apache.flink.table.types.inference.TypeInferenceUtil.inferOutputType(TypeInferenceUtil.java:154) at org.apache.flink.table.planner.functions.inference.TypeInferenceReturnInference.inferReturnTypeOrError(TypeInferenceReturnInference.java:99) at org.apache.flink.table.planner.functions.inference.TypeInferenceReturnInference.inferReturnType(TypeInferenceReturnInference.java:76) ... 62 more

**Comment by jiayuasu** [comment]
I reproduced the `ST_S2CellIDs` output-type-inference error from the later stack trace with Flink 1.19.3, both with released Sedona 1.9.1 and freshly built Sedona common/Flink modules at [228bfbcc42](https://github.com/apache/sedona/commit/228bfbcc42f0f0b537b1307f9738a5843f521e43).

The trigger in this test is **submitting the same jar twice through the REST jar endpoint to the same JobManager**.

Environment:

- Java 11.0.29, macOS arm64; one JobManager and two TaskManager JVMs on one machine, one slot each, parallelism 2. The successful jobs exercised network exchange between operators and workers.
- Clean Flink 1.19.3 distribution with default child-first user-code loading; no Sedona or JTS jars in the cluster `lib` directory.
- Maven Shade job containing Sedona and its dependencies, including `gt-referencing:33.1`, with service descriptors merged. Flink dependencies have `provided` scope; the job jar contains no Flink classes. Released Sedona uses JTS 1.20.0.
- Submission through `POST /jars/upload` and `POST /jars/{jarid}/run`, so application planning runs through `JarRunHandler`, as in the reported trace.

The workload registers Sedona types/functions, creates geometry rows using `ST_GeomFromWKT`, and follows the example's Table API → temporary view → UNNEST pattern:

```java
Table cells = geom.select(
    $("geom_point"), $("name_point"),
    call("ST_S2CellIDs", $("geom_point"), 10).as("s2id_array"));
t.createTemporaryView("pointTable", cells);
Table exploded = t.sqlQuery(
    "SELECT geom_point, name_point, s2id_point "
        + "FROM pointTable CROSS JOIN UNNEST(pointTable.s2id_array) "
        + "AS tmpTbl1(s2id_point)");
```

For both Sedona versions, the first run and repeat behaved as follows:

1. Start a fresh JobManager and run the uploaded jar: the job finishes. Both TaskManagers verify geometry and S2 results: 2,048 rows total, 1,024 per TaskManager, for each of the array and UNNEST outputs. `POINT (0.1 0.1)` at level 10 returns `1152927002164985856`.
2. Run the **identical uploaded jar** again, keeping the same JobManager: HTTP 400 during `sqlQuery` planning, before a job ID is created:

```text
ValidationException: Invalid function call:
ST_S2CellIDs(RAW('org.locationtech.jts.geom.Geometry', '...'), INT NOT NULL)
Caused by: ValidationException:
Could not infer an output type for the given arguments.
```

For the released artifact, restarting only the JobManager restored a successful run; repeating it failed again. The current-source artifact was tested with a fresh JobManager success followed by the identical-jar failure.

The successful and failing invocations load Geometry and the UDF from the same jar through different `ChildFirstClassLoader` instances. This suggests planner/type state retained across job classloaders. Flink/Calcite's RAW-type canonicalization cache is a candidate, but I have not confirmed the failing cache entry at runtime. Function registration succeeds in this reproduction; the failure is during output-type inference when expanding the view.

This gives us a current reproducer for the reported error. It does not establish that the original deployment had the same repeated-submission trigger.

**Comment by jiayuasu** [comment]
I verified a deployment workaround for the repeated-submission failure above on **unmodified Flink 1.19.3**:

1. Install the same Sedona, JTS, and required runtime dependency jars in `$FLINK_HOME/lib` on every JobManager and TaskManager.
2. Exclude those shared libraries from the submitted application jar. For Maven builds, use `provided` dependencies and check that the shaded job jar does not contain duplicate Sedona/JTS classes.
3. Restart the cluster after changing its libraries, then submit the application jar.

This loads the geometry classes from the persistent cluster classloader, so separate job submissions reuse the same classes. All jobs using this setup must use compatible shared dependency versions. Setting `classloader.resolve-order: parent-first` alone is insufficient if the libraries are still available only inside each job jar. See [Flink's shared-library guidance](https://nightlies.apache.org/flink/flink-docs-release-1.19/docs/ops/debugging/debugging_classloading/#avoiding-dynamic-classloading-for-user-code).

Validation used Java 11 and the same Sedona common/Flink build at [228bfbcc42](https://github.com/apache/sedona/commit/228bfbcc42f0f0b537b1307f9738a5843f521e43), with one JobManager and two TaskManager JVMs on one machine, parallelism 2. After separating the unchanged dependency classes from the application jar, **three consecutive REST submissions to the same JobManager succeeded**. Each run checked all 2,048 rows for both the array and UNNEST outputs, including geometry and S2 results; both TaskManagers participated. No Sedona or Flink code changes were needed for this workaround.

Further debugging confirmed that, in this reproducer, Flink/Calcite's shared type cache reused a geometry type from the previous job's classloader. A framework fix is proposed in [apache/flink#29150](https://github.com/apache/flink/pull/29150), which is currently open. The shared-library setup avoids triggering that cache mismatch while the upstream fix is pending.
