### ISSUE TITLE
Undeclared IPython dependency

### ISSUE THREAD

**Issue by sebbegg** [apache/sedona#1253]
## Expected behavior
Package documentation / metadata should match actual dependencies.

## Actual behavior

When installing apache-sedona along with its official requirements, IPython is not installed.
Importing sedona though also triggers an IPython import:

```commandline
Traceback (most recent call last):
  File "/Users/xyz/Projekte/sedona-migration/run_migration_to_3.5.py", line 3, in <module>
    from sedona.spark import SedonaContext
  File "/Users/xyz/Library/Caches/pypoetry/virtualenvs/sedona-migration-M_RNyLtM-py3.9/lib/python3.9/site-packages/sedona/spark/__init__.py", line 43, in <module>
    from sedona.raster_utils.SedonaUtils import SedonaUtils
  File "/Users/xyz/Library/Caches/pypoetry/virtualenvs/sedona-migration-M_RNyLtM-py3.9/lib/python3.9/site-packages/sedona/raster_utils/SedonaUtils.py", line 18, in <module>
    from IPython.display import display, HTML
ModuleNotFoundError: No module named 'IPython'
```

This is very inconvenient especially since `IPython` seems to be around only for the limited use-case of displaying images in an IPython environment.
It feels like sedona python should be usable with ipython though - or the IPython dependency should be properly documented in the package. 

Would you be open to accept a PR that moves the IPython import in 
https://github.com/apache/sedona/blob/87104212e30f0ea571164d6952c62dbb69ec1428/python/sedona/raster_utils/SedonaUtils.py#L18-L23

as a local import into the `display_image` classmethod?
That way the python lib - expect for the this specific feature - would still be usable without IPython. 

## Steps to reproduce the problem

```commandline
pip install apache-sedona==1.5.1 pyspark
python -c "import sedona.spark"
```
## Settings

Sedona version = 1.5.1

Apache Spark version = 3.3.2

Apache Flink version = ?

API type = Python

**Comment by sebbegg** [comment]
thanks @jiayuasu  - any idea when this will be released?
