### ISSUE TITLE
NullPointer Exception When Creating HeatMap

### ISSUE THREAD

**Issue by kanghq** [apache/sedona#164]
Babylon 0.2.1
GeoSpark 0.6.2
Spark 2.0.1
Followed the template to create a heat map but an error occurred.
Wondering any specific requirement for the input PolygonRDD?
I think the error occurred at Visualize function, Colorize()
Line 512
                this.maxPixelCount = this.distributedRasterCountMatrix.max(new RasterPixelCountComparator())._2;

		Envelope BJBoundary = new Envelope(114.24,118.24,37.54,41.54);
		HeatMap visualizationOperator = new HeatMap(1000,600,BJBoundary,false,2);
		visualizationOperator.Visualize(sc, mypolygonRDD);
		BabylonImageGenerator imageGenerator = new  BabylonImageGenerator();
		imageGenerator.SaveRasterImageAsLocalFile(visualizationOperator.rasterImage, outputPath,ImageType.PNG);

java.lang.NullPointerException
	at org.datasyslab.babylon.utils.Pixel.equals(Pixel.java:140)
	at org.apache.spark.util.collection.AppendOnlyMap.changeValue(AppendOnlyMap.scala:143)
	at org.apache.spark.util.collection.SizeTrackingAppendOnlyMap.changeValue(SizeTrackingAppendOnlyMap.scala:32)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap.insertAll(ExternalAppendOnlyMap.scala:163)
	at org.apache.spark.Aggregator.combineCombinersByKey(Aggregator.scala:50)
	at org.apache.spark.shuffle.BlockStoreShuffleReader.read(BlockStoreShuffleReader.scala:85)
	at org.apache.spark.rdd.ShuffledRDD.compute(ShuffledRDD.scala:109)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kanghq** [comment]
please add following sentences in the Pixel Class equals function.
You did not check the type of Object O, which will cause above exception!

if(!(o instanceof Pixel))
			return false;

**Comment by geoHeil** [comment]
Probably caused by kryo

**Comment by jiayuasu** [comment]
@kanghq After adding this line, will you still be able to see the correct image?

**Comment by kanghq** [comment]
@jiayuasu yup image shows correctly.

@geoHeil I think NULL check is always required in Java when overriding equals function. no matter what serialization tool you use.

https://users.soe.ucsc.edu/~eaugusti/archive/102-winter16/misc/howToOverrideEquals.html
How To Override the equals method inherited from the Object class...

**Comment by jiayuasu** [comment]
@kanghq Thanks for the reminder. Do you mind sharing some of your data with me so that I can reproduce this issue?

Because GeoSparkViz does have unit tests for many different datasets and every release passed tests. I am very curious about what triggers this problem.
