### ISSUE TITLE
Cryptic error message not sure what I am missing in my setup

### ISSUE THREAD

**Issue by lockwobr** [apache/sedona#269]
I am getting this error when a Transform it seems, not sure what jar i am missing.

```
spark.sql("select ST_Distance(ST_Transform(ST_Point(-84.2938, 34.0754), 'epsg:4326','epsg:3857'), ST_Transform(geom , 'epsg:4326','epsg:3857') ), address, address_lat, address_long from training limit 100).show(100)
```
sbt deps using sbt assemble
```
  "org.datasyslab" % "geospark" % "1.1.3",
  "org.datasyslab" % "geospark-sql_2.3" % "1.1.3",
```

Error message:
**org.opengis.referencing.NoSuchAuthorityCodeException: Authority "EPSG" is unknown or doesn't match the supplied hints. Maybe it is defined in an unreachable JAR file?**
```
org.opengis.referencing.NoSuchAuthorityCodeException: Authority "EPSG" is unknown or doesn't match the supplied hints. Maybe it is defined in an unreachable JAR file?
	at org.geotools.referencing.factory.ManyAuthoritiesFactory.noSuchAuthority(ManyAuthoritiesFactory.java:489)
	at org.geotools.referencing.factory.ManyAuthoritiesFactory.getAuthorityFactory(ManyAuthoritiesFactory.java:467)
	at org.geotools.referencing.factory.ManyAuthoritiesFactory.getCRSAuthorityFactory(ManyAuthoritiesFactory.java:548)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:801)
	at org.geotools.referencing.factory.ThreadedAuthorityFactory.createCoordinateReferenceSystem(ThreadedAuthorityFactory.java:731)
	at org.geotools.referencing.DefaultAuthorityFactory.createCoordinateReferenceSystem(DefaultAuthorityFactory.java:179)
	at org.geotools.referencing.CRS.decode(CRS.java:525)
	at org.geotools.referencing.CRS.decode(CRS.java:453)
	at org.apache.spark.sql.geosparksql.expressions.ST_Transform.eval(Functions.scala:189)
	at org.apache.spark.sql.geosparksql.strategy.join.DistanceJoinExec$$anonfun$toCircleRDD$1.apply(DistanceJoinExec.scala:65)
	at org.apache.spark.sql.geosparksql.strategy.join.DistanceJoinExec$$anonfun$toCircleRDD$1.apply(DistanceJoinExec.scala:64)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:214)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$21.apply(RDD.scala:1116)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$21.apply(RDD.scala:1116)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2130)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2130)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

GeoSpark version = 1.13

Apache Spark version = 2.3.1

JRE version = 1.8+ not sure using emr 5.16.0

API type = Scala

**Comment by lockwobr** [comment]
I resolved problem, the problem is the merge strategy that I was using was not correct, figured this out from this [faq](http://docs.geotools.org/stable/userguide/faq.html#how-do-i-create-an-executable-jar-for-my-geotools-app). To fix the problem I moved the project over to pom so I could use the same [shading](https://github.com/DataSystemsLab/GeoSpark/blob/1.1.3-spark-2.3/pom.xml#L175-L209) config as you guys have in this project.

Easy way to test is in spark shell
```
scala> import org.geotools.referencing.CRS

scala> val targetCRScode = CRS.decode("epsg:3857")
org.opengis.referencing.NoSuchAuthorityCodeException: Authority "EPSG" is unknown or doesn't match the supplied hints. Maybe it is defined in an unreachable JAR file?
  at org.geotools.referencing.factory.ManyAuthoritiesFactory.noSuchAuthority(ManyAuthoritiesFactory.java:489)
  at org.geotools.referencing.factory.ManyAuthoritiesFactory.getAuthorityFactory(ManyAuthoritiesFactory.java:467)
  at org.geotools.referencing.factory.ManyAuthoritiesFactory.getCRSAuthorityFactory(ManyAuthoritiesFactory.java:548)
  at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:801)
  at org.geotools.referencing.factory.ThreadedAuthorityFactory.createCoordinateReferenceSystem(ThreadedAuthorityFactory.java:731)
  at org.geotools.referencing.DefaultAuthorityFactory.createCoordinateReferenceSystem(DefaultAuthorityFactory.java:179)
  at org.geotools.referencing.CRS.decode(CRS.java:525)
  at org.geotools.referencing.CRS.decode(CRS.java:453)
  ... 49 elided
```

once fixed you get:

```
scala> import org.geotools.referencing.CRS
import org.geotools.referencing.CRS

scala> val targetCRScode = CRS.decode("epsg:3857")
targetCRScode: org.opengis.referencing.crs.CoordinateReferenceSystem =
PROJCS["WGS 84 / Pseudo-Mercator",
  GEOGCS["WGS 84",
    DATUM["World Geodetic System 1984",
      SPHEROID["WGS 84", 6378137.0, 298.257223563, AUTHORITY["EPSG","7030"]],
      AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]],
    UNIT["degree", 0.017453292519943295],
    AXIS["Geodetic latitude", NORTH],
    AXIS["Geodetic longitude", EAST],
    AUTHORITY["EPSG","4326"]],
  PROJECTION["Popular Visualisation Pseudo Mercator", AUTHORITY["EPSG","1024"]],
  PARAMETER["semi_minor", 6378137.0],
  PARAMETER["latitude_of_origin", 0.0],
  PARAMETER["central_meridian", 0.0],
  PARAMETER["scale_factor", 1.0],
  PARAMETER["false_easting", 0.0],
  PARAMETER["false_northing", 0.0],
  UNIT["m", 1....
```

Might want to include this in the getting starting docs for others.

**Comment by jiayuasu** [comment]
@lockwobr Thanks! Will do

**Comment by ps-spark** [comment]
Hi @jiayuasu ,

I'm suddenly getting this error today but I was able to run my code (fat jar) the whole week. It's strange. I'm trying to do a  CRS tranformation:

`lineRDD.CRSTransform("epsg:4326", "epsg:3857")`

Is there any special sbt parameter in assembly I have to use?

**Comment by ps-spark** [comment]
I'm still stuck here. I have tried the following shading in sbt assembly without any success:

`assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("org.opengis.referencing.**" -> "de.audi.analytics.geospark.referencing.@1").inAll
)`

**Comment by jiayuasu** [comment]
@ps-spark Please make sure all GeoTools jar listed here are included in the fat jar. You can uncompress the jar to check: https://github.com/DataSystemsLab/GeoSpark/blob/master/core/pom.xml#L80

If they are not there, you have to manually include these jar again in your POM. I don't know why, but apparently, many people who use Geotools have the same issue.

**Comment by ps-spark** [comment]
Hi @jiayuasu,

Thank you. I made a small research and the problem was that in our project we exclude all contents from the META-INF folders in the fat jar. So I added the following sbt code to build.sbt

```
assemblyMergeStrategy in assembly := {
  // GeoTools modules often define one or more files in its META-INF/services directory
  // with the same names as files defined in other modules
  // http://docs.geotools.org/latest/userguide/build/faq.html#how-do-i-create-an-executable-jar-for-my-geotools-app

  case PathList("META-INF", xs @ _*) => MergeStrategy.first
  case x =>
    val oldStrategy = (assemblyMergeStrategy in assembly).value
  oldStrategy(x)
}
```

**Comment by krishnaram** [comment]
I am getting this error. In intellij works fine in Spark node it is failing
