### ISSUE TITLE
JoinQuery throw java.lang.ClassCastException 

### ISSUE THREAD

**Issue by chahelagan** [apache/sedona#310]
## Expected behavior
i am use geospark in scala code call java api distacnce join throw java.lang.ClassCastException?

## Actual behavior
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [J
	at org.apache.spark.unsafe.memory.HeapMemoryAllocator.allocate(HeapMemoryAllocator.java:55)
	at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:300)
	at org.apache.spark.memory.MemoryConsumer.allocatePage(MemoryConsumer.java:117)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.acquireNewPageIfNecessary(UnsafeExternalSorter.java:383)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.insertRecord(UnsafeExternalSorter.java:407)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.insertRow(UnsafeExternalRowSorter.java:135)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.sort(UnsafeExternalRowSorter.java:217)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$2.apply(ShuffleExchangeExec.scala:295)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$2.apply(ShuffleExchangeExec.scala:266)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:830)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:830)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.commons.lang3.tuple.Pair
	at org.datasyslab.geospark.spatialOperator.JoinQuery$6.call(JoinQuery.java:520)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1043)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1043)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.sort(UnsafeExternalRowSorter.java:216)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$2.apply(ShuffleExchangeExec.scala:295)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$2.apply(ShuffleExchangeExec.scala:266)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:830)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:830)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
## Steps to reproduce the problem
distance join rdd a and b user core api JoinQuery.DistanceJoinQueryFlat

## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.3.0

JRE version = 1.8.0_60

API type = Java

**Comment by chahelagan** [comment]
// my sample code like this thanks
val logFrame = spark.read.parquet(sourceDataPath)
      .where($"phone".isNotNull and $"lat" <= 90 and $"lng" <= 180 and $"accessTime" >= rightWindow._1 and $"accessTime" <= rightWindow._2)
      .select($"phone", $"lat", $"lng", $"accessTime")
      .persist(StorageLevel.MEMORY_AND_DISK_SER)

    val leftRDD = logFrame.where($"accessTime" >= batchDuration._1 and $"accessTime" < batchDuration._2)
      .rdd
      .mapPartitions(partition => transformRawDataToPoint(partition, accumulatorService, StatisticKey.behavior_log_total_left))


    val rightRDD = logFrame
      .rdd
      .mapPartitions(partition => transformRawDataToPoint(partition, accumulatorService, StatisticKey.behavior_log_total_right))

    val sourcePointRDD = new PointRDD(leftRDD, StorageLevel.DISK_ONLY_2)
    val poiPointRDD = new PointRDD(rightRDD, StorageLevel.DISK_ONLY_2)
    sourcePointRDD.CRSTransform(SOURCE_CRS_CODE, TARGET_CRS_CODE)
    poiPointRDD.CRSTransform(SOURCE_CRS_CODE, TARGET_CRS_CODE)
    sourcePointRDD.analyze()

    val circleRDD = new CircleRDD(sourcePointRDD, distance) // Create a CircleRDD using the given distance
    circleRDD.analyze()
    circleRDD.spatialPartitioning(GridType.QUADTREE)
    poiPointRDD.spatialPartitioning(circleRDD.getPartitioner)

    val considerBoundaryIntersection = false // Only return gemeotries fully covered by each query window in queryWindowRDD
    val buildOnSpatialPartitionedRDD = true // Set to TRUE only if run join query
    val usingIndex = true

    circleRDD.buildIndex(IndexType.RTREE, buildOnSpatialPartitionedRDD)
    circleRDD.indexedRDD.persist(StorageLevel.MEMORY_AND_DISK_SER)
    poiPointRDD.spatialPartitionedRDD.persist(StorageLevel.MEMORY_AND_DISK_SER)

    val resultRDD = JoinQuery.DistanceJoinQueryFlat(poiPointRDD, circleRDD, usingIndex, considerBoundaryIntersection).rdd

    logFrame.unpersist()
    poiPointRDD.spatialPartitionedRDD.unpersist()
    poiPointRDD.rawSpatialRDD.unpersist()
    circleRDD.indexedRDD.unpersist()
    circleRDD.spatialPartitionedRDD.unpersist()
    circleRDD.rawSpatialRDD.unpersist()

**Comment by jiayuasu** [comment]
@chahelagan I am not sure why you saw this error. It looks similar to our test cases here: https://github.com/DataSystemsLab/GeoSpark/blob/master/sql/src/test/scala/org/datasyslab/geosparksql/adapterTestScala.scala#L156
