### ISSUE TITLE
ClassNotFound and URLClassLoader  for analyze and heatmap

### ISSUE THREAD

**Issue by fmarchand** [apache/sedona#362]
## Expected behavior
To not have exception :)

## Actual behavior

I'm working on NYC Yellow cabs files. I create a dataframe containing only points in a window : 

```
val spatialDf = spark.sql("""SELECT 
            | ST_Point(cast(raw_trips.pickup_longitude as Decimal(24,20)),cast(raw_trips.pickup_latitude as Decimal(24,20))) as shape 
            | FROM raw_trips 
            | WHERE (cast(raw_trips.pickup_longitude as Decimal(24,20)) > -74.220614) 
            |  AND (cast(raw_trips.pickup_longitude as Decimal(24,20)) < -73.548644)       
            |  AND (cast(raw_trips.pickup_latitude as Decimal(24,20)) < 40.951629) 
            |  AND (cast(raw_trips.pickup_latitude as Decimal(24,20)) > 40.466458)""".stripMargin)
```

Then I transform this dataframe in spatialRDD like this : 
```
import com.vividsolutions.jts.geom.Geometry
import org.datasyslab.geospark.spatialRDD.SpatialRDD
import org.datasyslab.geosparksql.utils.Adapter

var spatialRDD = new SpatialRDD[Geometry]
spatialRDD.rawSpatialRDD = Adapter.toRdd(spatialDf)
```

And after I try to do an "analyze" on it : 
```spatialRDD.analyze()```

Here is what I get : 
```
Name: org.apache.spark.SparkException
Message: Job aborted due to stage failure: ClassNotFound with classloader: scala.reflect.internal.util.ScalaClassLoader$URLClassLoader@38a1c7ea
StackTrace:   at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1517)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1505)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1504)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1504)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1732)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1687)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1676)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2030)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2127)
  at org.apache.spark.rdd.RDD$$anonfun$aggregate$1.apply(RDD.scala:1115)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.aggregate(RDD.scala:1108)
  at org.apache.spark.api.java.JavaRDDLike$class.aggregate(JavaRDDLike.scala:426)
  at org.apache.spark.api.java.AbstractJavaRDDLike.aggregate(JavaRDDLike.scala:45)
  at org.datasyslab.geospark.spatialRDD.SpatialRDD.analyze(SpatialRDD.java:502)
```
I have the same kind of error if I try : 
```
import org.datasyslab.geosparkviz.core.ImageGenerator;
import org.datasyslab.geosparkviz.extension.visualizationEffect.HeatMap;
import org.datasyslab.geosparkviz.utils.ImageType;
import com.vividsolutions.jts.geom.Envelope

val boundary = new Envelope(-74.220614, 40.951629, -73.548644, 40.466458)

val visualizationOperator:HeatMap = new HeatMap(800, 500, boundary, false, 2)
visualizationOperator.Visualize(sc, spatialRDD);
```

Here is the exception : 
```
Name: org.apache.spark.SparkException
Message: Job aborted due to stage failure: ClassNotFound with classloader: scala.reflect.internal.util.ScalaClassLoader$URLClassLoader@38a1c7ea
StackTrace:   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1505)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1504)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1504)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1732)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1687)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1676)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2030)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2127)
  at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1026)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.reduce(RDD.scala:1008)
  at org.apache.spark.rdd.RDD$$anonfun$max$1.apply(RDD.scala:1442)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.max(RDD.scala:1441)
  at org.apache.spark.api.java.JavaRDDLike$class.max(JavaRDDLike.scala:655)
  at org.apache.spark.api.java.AbstractJavaRDDLike.max(JavaRDDLike.scala:45)
  at org.datasyslab.geosparkviz.core.VisualizationOperator.Colorize(VisualizationOperator.java:579)
  at org.datasyslab.geosparkviz.extension.visualizationEffect.HeatMap.Visualize(HeatMap.java:138)
```

## Steps to reproduce the problem
I use a JupyterLab within a DC/OS cluster and it use Apache Toree for the Scala/Spark Kernel so to reproduce it, I guess it's not that easy ... 

## Settings

GeoSpark version = 1.2.0

Apache Spark version = 2.2.1

JRE version = 1.8

API type = Scala

## Question
So It looks like a package was not loaded but, I have nothing  telling me which one ... 
Maybe you've already seen that kind of exception ...

**Comment by jiayuasu** [comment]
I don't believe this is a GeoSpark bug. Probably you didn't load the GeoSpark-core, GeoSpark-SQL jar and GeoSPark-Viz jar correctly?
