### ISSUE TITLE
org.apache.spark.SparkException: com.vividsolutions.jts.geom.Geometry is not annotated with SQLUserDefinedType nor registered with UDTRegistration

### ISSUE THREAD

**Issue by Corvexmanu** [apache/sedona#371]
## Expected behavior

I am trying to do a spatial intersection between two datasets. My first step is to load the first  spatial dataset of coast lines and I want to create a column to identify whether or not each one is a valid geometry only for the QLD state. 

## Actual behavior

However, I am getting an error when the SQl statements executes.  

[root@node1 spark2]# ./bin/spark-submit --master yarn --jars /home/spark/autogenerator/jars/geospark-1.2.0.jar,/home/spark/autogenerator/jars/geospark-sql_2.3-1.2.0.jar  --class "Main" "/home/spark/autogenerator/autogenerator_2.11-0.1.jar" local /Users/sparkuser/spark/data/autogenerator/AUS_Coastlines/AUS_Coastlines /Users/sparkuser/spark/data/autogenerator/QLD_CADL/QLD_CADL /Users/sparkuser/spark/data/autogenerator/Results
Initiating...
Initiate dataset 1 loading...
**Exception in thread "main" org.apache.spark.SparkException: com.vividsolutions.jts.geom.Geometry is not annotated with SQLUserDefinedType nor registered with UDTRegistration**.}
        at org.apache.spark.sql.catalyst.encoders.RowEncoder$$anonfun$1.apply(RowEncoder.scala:84)
        at org.apache.spark.sql.catalyst.encoders.RowEncoder$$anonfun$1.apply(RowEncoder.scala:84)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.catalyst.encoders.RowEncoder$.org$apache$spark$sql$catalyst$encoders$RowEncoder$$serializerFor(RowEncoder.scala:83)
        at org.apache.spark.sql.catalyst.encoders.RowEncoder$$anonfun$2.apply(RowEncoder.scala:158)
        at org.apache.spark.sql.catalyst.encoders.RowEncoder$$anonfun$2.apply(RowEncoder.scala:157)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
        at org.apache.spark.sql.catalyst.encoders.RowEncoder$.org$apache$spark$sql$catalyst$encoders$RowEncoder$$serializerFor(RowEncoder.scala:157)
        at org.apache.spark.sql.catalyst.encoders.RowEncoder$.apply(RowEncoder.scala:61)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:592)
        at Main$.main(Main.scala:65)
        at Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:745)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[root@node1 spark2]#

## Steps to reproduce the problem

object Main {

  System.setProperty("geospark.global.charset", "utf8")

  Logger.getLogger("org").setLevel(Level.OFF)
  Logger.getLogger("akka").setLevel(Level.OFF)

  println("Initiating...")

  def main(args: Array[String]): Unit = {
    var sparkSession = SparkSession.builder()
      .master(args(0)) // Delete this if run in cluster mode
      .appName("readTestScala") // Change this to a proper name
      // Enable GeoSpark custom Kryo serializer
      .config("spark.serializer", classOf[KryoSerializer].getName)
      .config("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName)
      .getOrCreate()
    //
    // !!!!!!!!!!!!!!!!!!! END MAIN HERE !!!!!!!!!!!!!!!!!!!//

    FunctionRegistry.builtin.registerFunction("ST_GeomFromWKT", ST_GeomFromWKT)
    FunctionRegistry.builtin.registerFunction("ST_IsValid", ST_IsValid)

    // !!!!!!!!!!!!!!!!!!! Create first spatialRDD !!!!!!!!!!!!!!!!!!!
    println("Initiate dataset 1 loading...")
    val coastlinePath = args(1)
    val coastlineDf = ShapefileReader.readToGeometryRDD(sparkSession.sparkContext, coastlinePath)

    var rawCoastlineDf = Adapter.toDf(coastlineDf, sparkSession)
    rawCoastlineDf.createOrReplaceTempView("rawCoastlinedf")

    var coastline = sparkSession.sql(
      """
        | SELECT ST_IsValid(ST_GeomFromWKT(geometry)) AS valid, ST_GeomFromWKT(geometry) AS geometry, NAME, STATE, STATE_CODE
        | FROM rawCoastlineDf
        | WHERE STATE like 'QLD'
      """.stripMargin)
    coastline.createOrReplaceTempView("coastline")
    coastline.show()
    coastline.printSchema()

    println("First dataset has been loaded and RDD has been converted to SQL dataframe!")

}

## Settings

GeoSpark version = 1.2.0

Apache Spark version = 2.1.2

JRE version = 1.8.0_191

API type = Scala

**Comment by jiayuasu** [comment]
@Corvexmanu 

Hi,

I notice that, you use 
```
FunctionRegistry.builtin.registerFunction("ST_GeomFromWKT", ST_GeomFromWKT)
FunctionRegistry.builtin.registerFunction("ST_IsValid", ST_IsValid)
```

to register the functions by yourself.

This is OK but the correct way to register GeometryUDT and functions should be:
```
GeoSparkSQLRegistrator.registerAll(sparkSession)
```


I understand that, in some rate circumstance, you may end up with using your own way to register. If you want to do so, you may need to use the code here to register Geometry UserDefinedType:
https://github.com/DataSystemsLab/GeoSpark/blob/master/sql/src/main/scala/org/datasyslab/geosparksql/UDT/UdtRegistrator.scala

**Comment by Corvexmanu** [comment]
Hi. Thanks for your soon reply. 

Actually, I was doing that before, but when I was using it, I was receiving the following error:

```
[root@node1 spark2]# ./bin/spark-submit --master yarn --jars /home/spark/autogenerator/jars/geospark-1.2.0.jar,/home/spark/autogenerator/jars/geospark-sql_2.3-1.2.0.jar  --class "Main" "/home/spark/autogenerator/autogenerator_2.11-0.1.jar" local /Users/sparkuser/spark/data/autogenerator/AUS_Coastlines/AUS_Coastlines /Users/sparkuser/spark/data/autogenerator/QLD_CADL/QLD_CADL /Users/sparkuser/spark/data/autogenerator/Results
Initiating...
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.FunctionRegistry.createOrReplaceTempFunction(Ljava/lang/String;Lscala/Function1;)V
        at org.datasyslab.geosparksql.UDF.UdfRegistrator$$anonfun$registerAll$1.apply(UdfRegistrator.scala:29)
        at org.datasyslab.geosparksql.UDF.UdfRegistrator$$anonfun$registerAll$1.apply(UdfRegistrator.scala:29)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.datasyslab.geosparksql.UDF.UdfRegistrator$.registerAll(UdfRegistrator.scala:29)
        at org.datasyslab.geosparksql.utils.GeoSparkSQLRegistrator$.registerAll(GeoSparkSQLRegistrator.scala:34)
        at Main$.main(Main.scala:48)
        at Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:745)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[root@node1 spark2]#
```
I solved this error by registering them independently, however doing that I still got the initial error. 


Just in case I could be using something incorrectly:

- I am using this sbt in my IDE:

```
name := "AutoGenerator"

version := "0.1"

scalaVersion := "2.11.12"

libraryDependencies += "org.apache.spark" %% "spark-core" % "2.1.2"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.1.2"
libraryDependencies += "org.datasyslab" % "geospark" % "1.2.0" % "compile"
libraryDependencies += "org.datasyslab" % "geospark-sql_2.3" % "1.2.0" % "compile"
```
- The version of my spark cluster is version 2.1.0.2.6.0.3-8.

- I am also using the geospark-1.2.0.jar, and geospark-sql_2.3-1.2.0.jar when I run the .jar in my cluster. 

I'd appreciate any additional comment or clue about how to solve this issue.

Regards
Manuel.

**Comment by jiayuasu** [comment]
@Corvexmanu This is a very obvious mistake. You are using Spark 2.1 and GeoSpark source code for Spark 2.3. Note that, Spark 2.1 doesn't use FunctionRegistry.createOrReplaceTempFunction. Please go to GeoSpark source code branch for Spark 2.1: https://github.com/DataSystemsLab/GeoSpark/blob/spark-2.1/sql/src/main/scala/org/datasyslab/geosparksql/UDF/UdfRegistrator.scala

You need to use
```
FunctionRegistry.builtin.registerFunction
```
to register functions in Spark 2.1
