### ISSUE TITLE
Unable to read Shapefile on hdfs with pyspark core API

### ISSUE THREAD

**Issue by nicolas-renard** [apache/sedona#439]
## Expected behavior
Should be able to read Shapefile succesfully
## Actual behavior

```
AttributeError                            Traceback (most recent call last)
<ipython-input-67-893bc332e970> in <module>
----> 1 ShapefileReader.readToGeometryRDD(spark.sparkContext, "hdfs://masked_ip:masked_port/folder_path/")

/opt/conda/lib/python3.7/site-packages/geospark/core/formatMapper/shapefileParser/shape_file_reader.py in readToGeometryRDD(cls, sc, inputPath)
     27         :return:
     28         """
---> 29         ShapefileReader.validate_imports()
     30         jvm = sc._jvm
     31         jsc = sc._jsc

/opt/conda/lib/python3.7/site-packages/geospark/utils/decorators.py in run_function(*args, **kwargs)
     33 
     34             if first_not_fulfill_value == -1:
---> 35                 return func(*args, **kwargs)
     36             else:
     37                 raise ModuleNotFoundError(f"Did not found {has_all_libs[first_not_fulfill_value]}, make sure that was correctly imported via py4j"

/opt/conda/lib/python3.7/site-packages/geospark/core/jvm/config.py in applier(*args, **kwargs)
     33                 logging.warning(f"This function is not available for {geo_spark_version}, "
     34                                 f"please use version higher than {version}")
---> 35                 raise AttributeError(f"Not available before {version} geospark version")
     36             result = function(*args, **kwargs)
     37             return result

AttributeError: Not available before 1.2.0 geospark version
```

And the logging :
```
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 611, in format
    s = self.formatMessage(record)
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 580, in formatMessage
    return self._style.format(record)
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 422, in format
    return self._fmt % record.__dict__
ValueError: unsupported format character '%' (0x25) at index 11
Call stack:
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 583, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 538, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 1782, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 787, in inner
    self.run()
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/opt/conda/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/opt/conda/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/opt/conda/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/opt/conda/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/conda/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-67-893bc332e970>", line 1, in <module>
    ShapefileReader.readToGeometryRDD(spark.sparkContext, "hdfs://masked_ip:masked_port/folder_path/")
  File "/opt/conda/lib/python3.7/site-packages/geospark/core/formatMapper/shapefileParser/shape_file_reader.py", line 29, in readToGeometryRDD
    ShapefileReader.validate_imports()
  File "/opt/conda/lib/python3.7/site-packages/geospark/utils/decorators.py", line 35, in run_function
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/geospark/core/jvm/config.py", line 33, in applier
    logging.warning(f"This function is not available for {geo_spark_version}, "
Message: 'This function is not available for None, please use version higher than 1.2.0'
Arguments: ()
```

## Steps to reproduce the problem
```
from pyspark.sql import SparkSession
from geospark.register import GeoSparkRegistrator
from geospark.core.formatMapper.shapefileParser import ShapefileReader

spark = SparkSession.builder.appName("test")\
    .config("spark.driver.extraClassPath", "/opt/conda/lib/python3.7/site-packages/geospark/jars/2_4/*")\
    .config("spark.executor.extraClassPath", "/opt/conda/lib/python3.7/site-packages/geospark/jars/2_4/*")\
    .getOrCreate()

GeoSparkRegistrator.registerAll(spark)

rdd.rawJvmSpatialRDD = ShapefileReader.readToGeometryRDD(spark.sparkContext, "hdfs://masked_ip:masked_port/folder_path/")
```
## Settings

GeoSpark version = 1.3.1

Apache Spark version = 2.4.5

JRE version = 1.8

API type = Python

**Comment by Imbruced** [comment]
I will look into that. If the jar is correct there should be an error with GeoSpark version handling from Python code.

**Comment by Imbruced** [comment]
Hi,
Actually its a bug bcs code does not recognise GeoSpark version I have few workarounds for you

```python
# Workaround 1 
import os

from pyspark.sql import SparkSession
from geospark.register import GeoSparkRegistrator
from geospark.core.formatMapper.shapefileParser import ShapefileReader

path_to_jars = "/opt/conda/lib/python3.7/site-packages/geospark/jars/2_4/"

jars = ["geospark-1.3.0.jar", "geo_wrapper_2.11-0.3.0.jar", "geospark-sql_2.3-1.3.0.jar"]

jars_string = ",".join([os.path.join(path_to_jars, el) for el in jars])

spark = SparkSession.builder.appName("test")\
    .config("spark.jars", ",".join([os.path.join(path_to_jars, el) for el in jars]))\
.getOrCreate()

GeoSparkRegistrator.registerAll(spark)

srdd = ShapefileReader.\
   readToGeometryRDD(spark.sparkContext, "hdfs://masked_ip:masked_port/folder_path/")
```

```python3
# Workaround 2
import os

from pyspark.sql import SparkSession
from geospark.register import GeoSparkRegistrator
from geospark.core.formatMapper.shapefileParser import ShapefileReader
from geospark.register import upload_jars

upload_jars()

spark = SparkSession.builder.appName("test")\
    .getOrCreate()

GeoSparkRegistrator.registerAll(spark)

srdd = ShapefileReader.\
   readToGeometryRDD(spark.sparkContext, "hdfs://masked_ip:masked_port/folder_path/")
```


```python3
# Workaround 3
import os

from pyspark.sql import SparkSession
from geospark.register import GeoSparkRegistrator
from geospark.core.formatMapper.shapefileParser import ShapefileReader

path_to_jars = "/opt/conda/lib/python3.7/site-packages/geospark/jars/2_4/"
jars = ["geospark-1.3.0.jar", "geo_wrapper_2.11-0.3.0.jar", "geospark-sql_2.3-1.3.0.jar"]

jars_string = "--jars " + ",".join([os.path.join(path_to_jars, el) for el in jars]) + " pyspark-shell"

os.environ["PYSPARK_SUBMIT_ARGS"] = (os.environ.get("PYSPARK_SUBMIT_ARGS", "") + jars_string).strip()

spark = SparkSession.builder.appName("test")\
    .getOrCreate()

GeoSparkRegistrator.registerAll(spark)

srdd = ShapefileReader.\
   readToGeometryRDD(spark.sparkContext, "hdfs://masked_ip:masked_port/folder_path/")
```

Or add jars to spark manualy,

Please let me know if it works

**Comment by nicolas-renard** [comment]
Hi @Imbruced ,

Workarounds 1, 2 and 3 are working perfectly ! Thank you for your quick reply !

Regards,

**Comment by Imbruced** [comment]
@nicolas-renard @jiayuasu 
Perfect, I will close the issue once I fix the bug.
