### ISSUE TITLE
Python API,  No clear error: when creating SpatialRDD from Dataframe using Adapter.toSpatialRdd 

### ISSUE THREAD

**Issue by firasomrane** [apache/sedona#452]
## Expected behavior
Get an RDD created and rdd.analyze() returns True
## Actual behavior
**It only works when setting the geometry column name to `geometry` which is not expected following the [documentation](https://datasystemslab.github.io/GeoSpark/tutorial/geospark-core-python/#from-sparksql-dataframe)**
Complete traceback
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<.....> in <module>
     19 )
     20 
---> 21 df1_rdd = Adapter.toSpatialRdd(df1)
     22 df1_rdd.analyze()
     23 

/.../geospark/utils/meta.py in __call__(self, *args, **kwargs)
    119                     else:
    120                         if self._is_static:
--> 121                             return method.__get__(self).__call__(*args, **kwargs)
    122                         return method(*args, **kwargs)
    123 

/....../geospark/utils/adapter.py in toSpatialRdd(cls, dataFrame)
     52         jvm = sc._jvm
     53 
---> 54         srdd = jvm.Adapter.toSpatialRdd(dataFrame._jdf)
     55 
     56         spatial_rdd = SpatialRDD(sc)

/......./py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/....../pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/....../py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:org.datasyslab.geosparksql.utils.Adapter.toSpatialRdd.
: java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at org.datasyslab.geosparksql.utils.Adapter$.toRdd(Adapter.scala:74)
	at org.datasyslab.geosparksql.utils.Adapter$.toSpatialRdd(Adapter.scala:148)
	at org.datasyslab.geosparksql.utils.Adapter$.toSpatialRdd(Adapter.scala:98)
	at org.datasyslab.geosparksql.utils.Adapter$.toSpatialRdd(Adapter.scala:81)
	at org.datasyslab.geosparksql.utils.Adapter.toSpatialRdd(Adapter.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```
## Steps to reproduce the problem

Just created a spark session with kryo serializer, created a  Geospark Dataframe with geometry column using `ST_GeomFromWKT` and then trying to convert it to a `SpatialRdd` to do a spatial index.
```
import pyspark
from pyspark.sql import SparkSession

from geospark.register import GeoSparkRegistrator
from geospark.utils.adapter import Adapter
from geospark.utils import GeoSparkKryoRegistrator, KryoSerializer

conf = pyspark.SparkConf().setAll([
    ('spark.driver.extraClassPath', KryoSerializer.getName),
    ('spark.kryo.registrator', GeoSparkKryoRegistrator.getName)
])
spark_session = SparkSession.builder.config(conf=conf).getOrCreate()
GeoSparkRegistrator.registerAll(spark_session)

# df1 already defined and contains columns geometry and geom_id
df1.createOrReplaceTempView("df1_view")
df1 = spark_session.sql(
    """
        SELECT ST_GeomFromWKT(geometry) as geom, geom_id
        FROM df1_view
    """
)
# create a spatialRdd using Adapter
df1_rdd = Adapter.toSpatialRdd(df1)
df1_rdd.analyze()
```
For df1 schema:
```
root
 |-- geom: geometry (nullable = false)
 |-- geom_id: string (nullable = true)
```

## Settings

GeoSpark version = 1.3.1

Apache Spark version = 2.4.5

JRE version = 1.8

API type = Python

**Comment by jiayuasu** [comment]
@Imbruced Pawel, any idea about this?

**Comment by Imbruced** [comment]
Hi,
By default to create SpatialRDD by passing DataFrame you have to use geometry type column with name geometry, that's how core geospark is implemented. If you want to pass your column name, you can pass it as a second argument (that way is recommended). 

`def toSpatialRdd(dataFrame: DataFrame, geometryFieldName: str) -> SpatialRDD:`

You are right, documentation has to be changed. Function description should be clear.
